#!/usr/bin/env bash
set -euo pipefail

REPORT="cost-audit-report-$(date +%F).md"
DIR="$(cd "$(dirname "$0")" && pwd)"

echo "# Multi-Cloud Cost Optimization Audit — $(date +%F)" > "$REPORT"
echo "" >> "$REPORT"
echo "> Generated by \`run-cost-audit.sh\` | CLIs used: az, aws, gcloud" >> "$REPORT"
echo "" >> "$REPORT"

# ── Azure ──────────────────────────────────────────────────────────────────
if command -v az &>/dev/null; then
    echo "## Azure" >> "$REPORT"
    echo "" >> "$REPORT"
    echo '```' >> "$REPORT"
    bash "$DIR/azure-cost-audit.sh" 2>&1 | tee -a "$REPORT" || echo "⚠ Azure audit failed" | tee -a "$REPORT"
    echo '```' >> "$REPORT"
    echo "" >> "$REPORT"
else
    echo "## Azure" >> "$REPORT"
    echo "" >> "$REPORT"
    echo "_az CLI not found. Skipping._" >> "$REPORT"
    echo "" >> "$REPORT"
fi

# ── AWS ────────────────────────────────────────────────────────────────────
if command -v aws &>/dev/null; then
    echo "## AWS" >> "$REPORT"
    echo "" >> "$REPORT"
    echo '```' >> "$REPORT"
    bash "$DIR/aws-cost-audit.sh" 2>&1 | tee -a "$REPORT" || echo "⚠ AWS audit failed" | tee -a "$REPORT"
    echo '```' >> "$REPORT"
    echo "" >> "$REPORT"
else
    echo "## AWS" >> "$REPORT"
    echo "" >> "$REPORT"
    echo "_aws CLI not found. Skipping._" >> "$REPORT"
    echo "" >> "$REPORT"
fi

# ── GCP ────────────────────────────────────────────────────────────────────
if command -v gcloud &>/dev/null; then
    echo "## GCP" >> "$REPORT"
    echo "" >> "$REPORT"
    echo '```' >> "$REPORT"
    bash "$DIR/gcp-cost-audit.sh" 2>&1 | tee -a "$REPORT" || echo "⚠ GCP audit failed" | tee -a "$REPORT"
    echo '```' >> "$REPORT"
    echo "" >> "$REPORT"
else
    echo "## GCP" >> "$REPORT"
    echo "" >> "$REPORT"
    echo "_gcloud CLI not found. Skipping._" >> "$REPORT"
    echo "" >> "$REPORT"
fi

echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "_Report generated at $(date '+%Y-%m-%d %H:%M:%S')_" >> "$REPORT"

echo "✅ Report written to $REPORT"
